[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "askcarl"
version = "3.0.1"
description = "Gaussian mixture models with support for missing values and upper limits in some features."
authors = [
    {name = "Johannes Buchner", email = "johannes.buchner.acad@gmx.com"}
]
license = "GPL-3.0"
readme = "README.rst"
requires-python = ">=3.7"
keywords = ["Multivariate Gaussians with support for upper limits and missing data"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "numpy",
    "jax",
    "scipy",
    "matplotlib",
    "reportlab",
    "scikit-learn",
]

[project.optional-dependencies]
plot = ["matplotlib", "scipy"]

[project.urls]
Homepage = "https://github.com/JohannesBuchner/askcarl"
Source = "https://github.com/JohannesBuchner/askcarl"
Documentation = "https://johannesbuchner.github.io/askcarl/"

[tool.pytest]
collect_ignore = ["setup.py"]

[tool.bumpversion]
current_version = "3.0.1"
commit = true
tag = true
tag_name = "{new_version}"
message = "Bump version: {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "askcarl/__init__.py"
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"
